//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatRoom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public Conversation()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public string ConversationID { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
    
        public virtual User UserOne { get; set; }
        public virtual User UserTwo { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
