//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatRoom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string MessageID { get; set; }
        public string Sender { get; set; }
        public string Reciever { get; set; }
        public string MessageText { get; set; }
        public string ParentConversation { get; set; }
        public System.DateTime DateSent { get; set; }
    
        public virtual Conversation Conversation { get; set; }
    }
}
